# Generated by Django 2.2.4 on 2024-04-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240413_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subimage_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subimage_2',
        ),
    ]
