# Generated by Django 2.2.4 on 2024-04-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240415_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='url',
        ),
    ]
